### ISSUE TITLE
Documentation of esp-hal once unified

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1205]
## READMEs

- [x] https://github.com/esp-rs/esp-hal/pull/1217
- [x] https://github.com/esp-rs/esp-hal/pull/1228
- [x] esp-rs/esp-hal#1237

## lib docs

- [ ] https://github.com/esp-rs/esp-hal/issues/1242
    - JB: This can probably wait until post-release?
- [ ] https://github.com/esp-rs/esp-hal/issues/1225
    - JB: See above

## external

- [x] esp-rs/esp-hal#1218
- [ ] esp-rs/esp-template#148
- [ ] esp-rs/esp-hal#1222
- [x] esp-rs/esp-hal#1220

**Comment by JurajSadel** [comment]
I'm going to start with READMEs

**Comment by jessebraham** [comment]
I've moved some of the documentation tasks to a separate issue: https://github.com/esp-rs/esp-hal/issues/1221

**Comment by jessebraham** [comment]
Fleshed out `examples/README.md` in #1237

**Comment by jessebraham** [comment]
READMEs have been updated.

**Comment by jessebraham** [comment]
@MabezDev @bjoernQ what are your thoughts on delaying the remaining two points here, in the interest of getting the release out? I think it's fine if we tackle them both post-release, personally.
