### ISSUE TITLE
DMA move API tracking issue

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#2269]
Basics

- #1716
- #1719
- #1856
- #1976

Peripheral support

- [x] SPI master
- [x] SPI slave #3326
- [x] I8080 #2191
  - #2268
- [x] Camera #2242
- [x] AES #3084
- [x] PARL IO #3033
- [ ] I2S
- [x] Memcpy #3329

Buffer features

- #2161
- [ ] Support other slice types besides `u8`.
- [x] [Support configuring burst mode](https://github.com/esp-rs/esp-hal/pull/2336)
- [x] [Support configuring the "check descriptor ownership" feature on the DMA channel](https://github.com/esp-rs/esp-hal/pull/2337)
- [x] [Support configuring the ownership write back feature in the DMA channel](https://github.com/esp-rs/esp-hal/pull/3107)
- [x] [Allow users to create the Preparation struct (make it public)](https://github.com/esp-rs/esp-hal/pull/2455)
- [ ] Expose an unsafe constructor for people to create buffers on the stack.
- [ ] Place the buffer view methods in internal ram since they're likely to be called in interrupts

Buffer types

- [ ] DmaTxStreamingBuf
- [ ] DmaTxCircularBuf
- [ ] DmaRxCircularBuf
- [ ] DmaReadOnlyBuf (for creating multiple bufs that point to the same buffer)
- [ ] Compressed buffer? Not sure if this should be in the hal

Note: This issue can be closed once the `DescriptorChain` struct is deleted.

**Comment by bugadani** [comment]
I thought we might want to track work that needs to be done in this area, but I'm unsure what that work actually is.

**Comment by Dominaezzz** [comment]
I've added all the stuff I had at the back of my mind

**Comment by bjoernQ** [comment]
While working on migrating the I2S driver to use the buffer / buffer-view mechanism a few problems got revealed

The fundamental assumption about buffers is that they are free (and actually in-charge) to modify the descriptor list _and_ otherwise don't deal with the actual DMA hw.

In the case of one-shot transfers this works fine - there is a preparation phase before starting the DMA-machinery and things will end up fine.

In the case of streaming-like buffers the buffers (i.e. the views) need to update the linked list "in-flight" - an example of this is https://docs.espressif.com/projects/rust/esp-hal/1.1.0/esp32c6/esp_hal/dma/struct.DmaRxStreamBuf.html (and the docs explain how the list is actually modified)

However there is a catch here because the hw will pre-fetch descriptors - having "enough" descriptors "between" what the code is modifying and what the hardware is currently accessing this works but otherwise this will cause problems.

Later TRMs even contain a hint here:

> In some cases, you may want to append more descriptors to a DMA transfer that is already started. Naively, it
would seem to be possible to do this by clearing the EOF bit of the final descriptor in the existing list and
setting its next descriptor address pointer field (DW2) to the first descriptor of the to-be-added list. However,
this strategy fails if the existing DMA transfer is almost or entirely finished. Instead, the GDMA controller has
specialized logic to make sure a DMA transfer can be continued or restarted: if the transfer is ongoing, the
controller will make sure to take the appended descriptors into account; if the transfer has already finished,
the controller will restart with the new descriptors. This is implemented by the Restart function.
>
> When using the Restart function, software needs to rewrite address of the first descriptor in the new list to
DW2 of the last descriptor in the loaded list, and set GDMA_INLINK_RESTART_CHn bit or
GDMA_OUTLINK_RESTART_CHn bit (these two bits are cleared automatically by hardware). As shown in Figure
4-4, by doing so hardware can obtain the address of the first descriptor in the new list when reading the last
descriptor in the loaded list, and then read the new list.

i.e. the buffer would need to "communicate" that it changed the descriptor list and RESTART needs to get set. With the current design this is not possible

The current API also allows the transfer-structs / impls to be agnostic about the used buffer implementation. This would also allow users to provide their own specialized / tuned buffer implementation - which is very nice but even more mandates the buffer being disjoint from the DMA-channel

**Comment by Dominaezzz** [comment]
Yes, the transfer structs need to expose some methods like `restart` to facilitate any buffer features like this. 

I hadn't gotten around to doing this yet because my ideas involve more DerefMut to make this happen without excessive repetition. 

Out of curiosity, how did you discover this prefetch issue. Was the transfer stalling?

**Comment by bjoernQ** [comment]
> Out of curiosity, how did you discover this prefetch issue. Was the transfer stalling?

Yes - depending on the number of descriptors it was just stalling without setting any error bits - it just "died" without any further notice 🤷‍♂️

**Comment by Dominaezzz** [comment]
No error bits being set sounds like a hardware bug to me. You should definitely see IN_DESC_EMPTY being set, as per the TRM.

I understand the prefetch means you have less breathing room when streaming but it should still set the right error bit.

Another path to go might be to have a DmaRxCircularBuf that doesn't modify the `next` pointers and only changes the owner bit. This is what the existing i2s circular transfer does.
The advantage of this is you get a different (hopefully less buggy) error when you're too slow.

**Comment by bjoernQ** [comment]
Yes - the fact that the error bits are not set is the worst part of this.

I agree a circular buffer should work better in this regard since with the previous/current solution we see it sets the expected error bits

**Comment by Dominaezzz** [comment]
Now that #5603 has landed, this issue can be closed.

There are still some loose ends to tie up like:
- SPI master's DMA API looks different from the rest, and it doesn't expose the view yet.
- esp-hal buffers only support `u8` at the moment, but people probably want `u16`, `u32`, etc.
- Consistently expose the DMA interrupts on all transfer objects.

But these can be tracked in separate individual issues with a defined end goal.
