### ISSUE TITLE
Stable driver: SPI master

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2494]
As part of #2491, which has more details on driver analysis.

Note: we are not stabilizing DMA support right now.

#### Construction 
- [x] #2673

#### Interop
- [ ] #2778
      - Something like embassy-hal spi bus has
      - Related to hardware cs management item below
      - Note from danielb: device shouldn't be implemented for bus driver structs.
- [x] #2675
- [x] #2678
- [x] #2791
- [x] #2792
#### API surface
- [x] Hide `Info` struct? - I think we probably want to sit on this a bit longer before exposing it as a stable API
- [x] #2679
- [x] #2680
- [x] #2685
    - SPI Master driver is also the only place where we're using `assert` (and its derivatives) macro. I believe we can avoid it (not talking about `debug` ones though)
#### Documentation
- [ ] cfg DMA mentions with the unstable flag (see #2793)
#### Maintainability 
- [ ] Prefer `cfg_if!` over MULTIPLE exclusive `#[cfg]` attributes (some of below snippets are not public, but still would be good to make them more maintainable)
  - Maybe just have 2 separate functions per feature instead? https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs#L2281-L2315
  - https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs#L103-L106
  - https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs#L2921-L2926
  - https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs#L2399-L2403 (well, the [whole function](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs#L2355-L2406) in fact, but I don't think it's worth it at this point tbh 😅 )

#### Driver Implementation
- [x] `State` struct is "yet-to-be-created" - changed in #2691
---
	
### Rust API guideline omissions
- [x] Missing `PartialEq` and `Eq` on `spi::master::Config` (#2791)
  - https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs#L46-L50
- [x] #2794
- [x] `C-CASE`: `SpiBitOrder` variants should be `MsbFirst` and `LsbFirst`
---

### Hardware feature omissions

- [x] https://github.com/esp-rs/esp-hal/issues/2511
- [ ] https://github.com/esp-rs/esp-hal/issues/2240
- [x] https://github.com/esp-rs/esp-hal/issues/2497
- [x] https://github.com/esp-rs/esp-hal/issues/1826
- [ ] #2795
  - Config option exposed, `0-2` for most Instances/chips but some support `0-5`
  - Need the pin linkage functions too, i.e `with_cs1`, `with_cs2` etc
- [ ] #2796
    - Allow configuration of the cs setup timings - Setup time of CS active edge before the first SPI clock
    - Allow configuration of the cs hold timings - Hold time of CS inactive edge after the last SPI clock
- [ ] #2797
    - Unsure how (or where) we can enforce this without our own version of embassy-hal spi bus - even then, this config won't always make sense
- [ ] #2798
- [x] #2799
- [ ] #2800
  - I don't think we need this for 1.0, but I'm listing it here so we can either decide we don't want to support it, or make sure we _can_ support it post 1.0
- [x] ~~Expose bit ordering for tx and rx~~
- [ ] #2801
    - MISO dummy delay
    - dummy delay
    - These are derived from a number of input params, including the expected bus speed etc so we need to take that into account.
- [ ] Half duplex modes
    - [x] #2687
    - Add tests for Half-Duplex Communication (1/2/4bit mode)
	- 8bit mode not required and device specific (s2, s3, p4) but worth considering in the impl to ensure we can add it
    - Expose "SPI_WP This bit determines the write-protection signal output when SPI is idle in QSPI mode."
- [ ] Missing clock source configuration cc: https://github.com/esp-rs/esp-hal/issues/1668
- [ ] #2809
- [ ] Data mode configuration is more general than needed. https://github.com/esp-rs/esp-hal/pull/2681#discussion_r1871435419
- [ ] #2802
    - danielb: Maybe we can do this using a separate API, like `read/write/transfer_bits` on devices that support it. (C6: `To transfer bits that is not an integral multiple of byte (8 bits), consider implementing it in CMD state or ADDR state.`)
- [ ] #2803

### Misc

- [x] #2804
  - Note (pF): Replace or wait till https://github.com/korken89/fugit/issues/52 is resolved (?) 

- [x] #2805

- [x] #2806

- [x] #2807

- [x] #2808

- [x] #2793
    -  `half_duplex_XXX` is marked unstable in `Spi` but not in other places (i.e. `SpiDmaXXX`)
        -  `with_sio2` / `with_sio3` is not marked unstable - but if `half_duplex_XXX` is unstable these should be marked, too
    - `Spi::with_dma` is marked unstable but not `SpiDmaXXX`
   
---

**Comment by bugadani** [comment]
> Note: we are not stabilizing DMA support right now.

What exactly does this mean, we're only aiming at stabilizing `spi::master::Spi`? That's a surprisingly small slice of the driver.

**Comment by MabezDev** [comment]
> What exactly does this mean, we're only aiming at stabilizing spi::master::Spi? That's a surprisingly small slice of the driver.

Start small, and incrementally stabilize. It's easier to stabilize `spi::master::Spi` and then `SpiDma` than both at the same time.

Remember folks can always opt in to `unstable` to use the rest of the driver. We need to be 100% certain what we're stabilizing is solid, there are no take-backsies till 2.0 :D.

**Comment by FloppyDisck** [comment]
Hello, I would prefer that `SPI` implemented `SpiDevice`. If needed I can help finish implementing whatever it needs to get added on the next version.

**Comment by Dominaezzz** [comment]
> Hello, I would prefer that `SPI` implemented `SpiDevice`. If needed I can help finish implementing whatever it needs to get added on the next version.

Does `ExclusiveDevice` not suit your needs?

**Comment by Dominaezzz** [comment]
> What I'm unsure about, is, whether we have to provide any chip select functionality for the bus driver in the first place.

I think so, otherwise how do people select which device they're talking to on the bus.

**Comment by bugadani** [comment]
With a GPIO, as they already do when using `ExclusiveDevice`.

**Comment by Dominaezzz** [comment]
Ah I see. 

Fwiw, when I created the issue asking to expose the CS signals, I meant adding it to `Spi` and `SpiDma`, alongside the keep_cs_active option.
Adding it to `SpiDmaBus` is a bit weird due to the chunking.

**Comment by bugadani** [comment]
They are still bus drivers, not device drivers. The busses shouldn't care much about chip select, that's the responsibility of the device drivers. Whether the chip select ends up being implemented as a hardware signal or a software GPIO write, isn't something the bus driver have to know about. For single transfers, there is essentially no difference (you still need to write a register to select a particular chip select and make sure that chunking doesn't deassert it, which is apparently impossible 😅), except with hardware chip select, you have less flexibility in the CS-to-SCLK delay.

**Comment by Dominaezzz** [comment]
Hmm, I guess I just want an inherent GSPI-2/3 driver without the connotations of "bus" and "device", which will let me select a CS pin and create my own "device"s.
Software CS is rather inconvenient for interrupt queues and I generally don't want to rely on my async scheduler to de-assert the CS pin in a timely fashion. Some of the devices I talk to wait patiently for the de-assert before taking action, which is latency I'd love to do without.
So there is a UX and timing difference, even for single transfers.

Also on the DMA side, whilst the `SpiDma` is busy waiting for the RX channel to finish writing to memory, I'd like that time to also be spent performing the CS hold time delay rather than have a separate additional/excess delay, which is only possible if the hardware is doing it really.

**Comment by playfulFence** [comment]
`C-QUESTION-MARK` violation is legal now: https://github.com/esp-rs/esp-hal/issues/2811#issuecomment-2582298034

Deleted it from this list

**Comment by Dominaezzz** [comment]
Just saw the first release candidate.

Don't forget to look at https://github.com/esp-rs/esp-hal/issues/2797 before 1.0 

I don't think it can be postponed
